/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Manuel W. (https://sketchfab.com/nebulariser)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/smartphone-380280333c9f4fb8a21a53d18f6789e6
title: Smartphone
*/

import React, {ForwardedRef, forwardRef} from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import {Mesh, MeshStandardMaterial, Texture} from "three";

type GLTFResult = GLTF & {
    nodes: {
        Object_4: Mesh;
        Object_6: Mesh;
        Object_7: Mesh;
        Object_8: Mesh;
        Object_9: Mesh;
        Object_10: Mesh;
        Object_11: Mesh;
        Object_12: Mesh;
        Object_13: Mesh;
        Object_14: Mesh;
        Object_16: Mesh;
        Object_18: Mesh;
        Object_19: Mesh;
        Object_21: Mesh;
        Object_22: Mesh;
        Object_24: Mesh;
        Object_26: Mesh;
        Object_28: Mesh;
        Object_30: Mesh;
        Object_32: Mesh;
        Object_33: Mesh;
        Object_35: Mesh;
        Object_37: Mesh;
        Object_39: Mesh;
    };
    materials: {
        Metal_Cromado: MeshStandardMaterial;
        Vidrio_Negro: MeshStandardMaterial;
        Pantalla: MeshStandardMaterial;
        Metal_Negro: MeshStandardMaterial;
        Bandas_magneticas: MeshStandardMaterial;
        Camara: MeshStandardMaterial;
        Luz_Led: MeshStandardMaterial;
        Metal_Ceramico: MeshStandardMaterial;
        Cobre: MeshStandardMaterial;
    };
};

type SmartphoneProps = JSX.IntrinsicElements["group"] & {
    children?: React.ReactNode;
    texture?: Texture;
};



export const Smartphone = forwardRef((props: SmartphoneProps, ref: ForwardedRef<any>) => {
    const { nodes, materials } = useGLTF("/smartphone.glb") as unknown as GLTFResult;
    return (
        <group {...props} ref={ref} dispose={null}>
            <group rotation={[Math.PI *1.5, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group
                        position={[0.5, 0.54, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[1, 0.67, 1]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_4.geometry}
                            material={materials.Metal_Cromado}
                        />
                    </group>
                    <group rotation={[Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_6.geometry}
                            material={materials.Vidrio_Negro}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_7.geometry}
                            material={materials.Vidrio_Negro}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_8.geometry}
                            material={materials.Vidrio_Negro}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_9.geometry}
                            material={materials.Metal_Cromado}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_10.geometry}
                            material={materials.Metal_Cromado}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_11.geometry}
                            material={materials.Pantalla}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_12.geometry}
                            material={materials.Pantalla}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_13.geometry}
                            material={materials.Metal_Negro}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_14.geometry}
                            material={materials.Bandas_magneticas}
                        />
                    </group>
                    <group rotation={[Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_16.geometry}
                            material={materials.Metal_Cromado}
                        />
                    </group>
                    <group position={[0, 1, 0]} rotation={[Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_18.geometry}
                            material={materials.Vidrio_Negro}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_19.geometry}
                            material={materials.Metal_Cromado}
                        />
                    </group>
                    <group
                        position={[0.38, 0.88, -0.06]}
                        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                        scale={0.06}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_21.geometry}
                            material={materials.Vidrio_Negro}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_22.geometry}
                            material={materials.Metal_Cromado}
                        />
                    </group>
                    <group
                        position={[0.38, 0.88, -0.05]}
                        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                        scale={0.04}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_24.geometry}
                            material={materials.Camara}
                        />
                    </group>
                    <group
                        position={[0.19, 0.91, -0.05]}
                        rotation={[-Math.PI / 2, -1.39, Math.PI]}
                        scale={0.03}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_26.geometry}
                            material={materials.Luz_Led}
                        />
                    </group>
                    <group
                        position={[0.27, 0.88, -0.05]}
                        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                        scale={0.04}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_28.geometry}
                            material={materials.Camara}
                        />
                    </group>
                    <group
                        position={[0, 0.85, 0.03]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[1.08, 1.03, 1.18]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_30.geometry}
                            material={materials.Camara}
                        />
                    </group>
                    <group
                        position={[0, -0.99, 0]}
                        rotation={[0, Math.PI / 2, 0]}
                        scale={0.01}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_32.geometry}
                            material={materials.Metal_Ceramico}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_33.geometry}
                            material={materials.Cobre}
                        />
                    </group>
                    <group
                        position={[0, -0.95, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[1.03, 1.1, 1.03]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_35.geometry}
                            material={materials.Metal_Negro}
                        />
                    </group>
                    <group position={[0.22, -0.99, 0]} rotation={[Math.PI / 2, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_37.geometry}
                            material={materials.Metal_Negro}
                        />
                    </group>
                    <group
                        position={[-0.22, -0.99, 0]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={[1.02, 1.1, 1.02]}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Object_39.geometry}
                            material={materials.Metal_Negro}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
});

useGLTF.preload("/smartphone.glb");